# Generated by Django 3.0.6 on 2020-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_auto_20200507_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='heading',
            field=models.CharField(max_length=1000),
        ),
    ]
