# Generated by Django 3.0.6 on 2020-06-07 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Room', '0003_auto_20200607_1004'),
        ('Service', '0002_auto_20200604_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAwaitingApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.Rooms')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
