# Generated by Django 3.0.6 on 2020-06-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_auto_20200614_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_using',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
