# Generated by Django 3.0.6 on 2020-06-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_service_using_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Using',
        ),
    ]
