# Generated by Django 3.0.6 on 2020-06-15 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20200607_1004'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Service', '0007_delete_service_using'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Using',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('status_register', models.BooleanField(default=False)),
                ('status_using', models.BooleanField(default=False)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.Rooms')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
